#!/usr/bin/env python3
"""
match_look.py — pull a finished render onto its style's measured numbers.

Why this is a separate tool and not a pipeline stage
----------------------------------------------------
It writes a NEW file and never touches the input, so it can be run on anything —
a free-route render, a Higgsfield output, a clip downloaded from an arena — and
reverting it means not running it. Nothing upstream has to know it exists.

What it is for
--------------
Scoring the renders we already had put saturation as the largest error term in
every one of them, about half the total distance from the account, and pointing
the wrong way: renders aimed at @johnnyharris (clips measure 0.29) came out at
0.65-0.72, and renders aimed at @guijooorge (clips measure 0.70) came out at
0.30-0.39. The two accounts had each other's saturation.

Saturation is corrected by measuring, not by guessing a multiplier. ffmpeg's
eq=saturation acts in YUV and the metric here is area-weighted HSV, so the two
are not linearly related — the tool applies a first guess, re-measures, refines
once, and keeps whichever pass landed closer.

Palette lock builds a 3D LUT that pulls colours near a measured palette entry
onto it, with a falloff so antialiasing and shading are left alone. On flat
vector material, where the top three colours already cover 84% of frame, this
is a small nudge; on photographic material it would be vandalism, so it is
off unless asked for.

Usage:
    match_look.py in.mp4 out.mp4 --style guijooorge-flat --saturation
    match_look.py in.mp4 out.mp4 --style guijooorge-flat --saturation --palette-lock
    match_look.py in.mp4 out.mp4 --target-saturation 0.70 --dry-run
    match_look.py --set-targets guijooorge-flat --from-channel guijooorge
"""
import argparse, json, os, subprocess, sys, tempfile
sys.path.insert(0, "/root/bulk-transcriber")
import numpy as np

_ARGS = sys.argv[1:]
sys.argv = [sys.argv[0]]
import measure_reference as M


def _run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def saturation_of(path):
    r = M.measure(path)
    if r.get("error"):
        raise SystemExit("could not measure %s: %s" % (path, r["error"]))
    return r["mean_saturation"], r


def apply_filters(src, dst, vf):
    p = _run(["ffmpeg", "-y", "-v", "error", "-i", src, "-vf", vf,
              "-c:v", "libx264", "-crf", "18", "-preset", "medium",
              "-c:a", "copy", dst])
    if p.returncode != 0:
        raise SystemExit("ffmpeg failed: %s" % p.stderr[:400])
    return dst


def write_cube(path, palette, strength=0.4, radius=0.16, size=33):
    """A 3D LUT that snaps near-palette colours onto the palette.

    Colours already close to a measured entry are pulled the rest of the way;
    colours further than `radius` are left exactly as they are, which is what
    keeps edges, shadows and antialiasing intact instead of posterised.
    """
    pal = np.array([[int(h[i:i + 2], 16) / 255.0 for i in (1, 3, 5)] for h in palette])
    g = np.linspace(0.0, 1.0, size)
    with open(path, "w") as f:
        f.write("# generated by match_look.py from the style's measured palette\n")
        f.write("LUT_3D_SIZE %d\n" % size)
        for b in g:
            for gg in g:
                for r in g:
                    c = np.array([r, gg, b])
                    d = np.linalg.norm(pal - c, axis=1)
                    j = int(np.argmin(d))
                    if d[j] < radius:
                        w = strength * (1.0 - d[j] / radius)
                        c = c * (1 - w) + pal[j] * w
                    f.write("%.6f %.6f %.6f\n" % tuple(np.clip(c, 0, 1)))
    return path


def api(path, payload=None):
    import app as A
    return A._api_post(path, payload, timeout=60) if payload else A._api_get(path)


def get_style(slug):
    st = next((s for s in api("/api/render-styles")["styles"] if s["slug"] == slug), None)
    if not st:
        raise SystemExit("no style %r" % slug)
    if isinstance(st.get("palette"), str):
        st["palette"] = json.loads(st["palette"] or "[]")
    return st


def set_targets(slug, channel, limit=5):
    """Measure the account and store what a render aimed at it must hit."""
    clips = [c for c in api("/api/reference-clips")["clips"]
             if (c["channel_name"] or "").lower().lstrip("@") == channel.lower().lstrip("@")]
    if not clips:
        raise SystemExit("no registered clips for %r" % channel)
    bysrc = {}
    for c in clips:
        bysrc.setdefault(c["source_file"], c)
    picked = list(bysrc.values())[:limit]
    if len(picked) < 3:
        print("WARNING: only %d source videos. The loop's own rule is 3 or more "
              "before stating a system; these targets are provisional." % len(picked))
    R = "/root/bulk-transcriber/refclips/"
    paths = []
    for c in picked:
        stem = c["asset_key"][4:] if c["asset_key"].startswith("ref_") else c["asset_key"]
        p = R + stem
        if not os.path.exists(p):
            import urllib.request
            p = "/tmp/" + stem
            urllib.request.urlretrieve(c["url"], p)
        paths.append(p)
    agg = M.aggregate([M.measure(p) for p in paths])
    st = get_style(slug)
    st["target_saturation"] = round(agg["mean_saturation"], 4)
    st["target_flatness"] = round(agg["flatness"]["top3"], 4)
    st["target_dark_area"] = round(agg["linework"]["dark_area"], 4)
    st["targets_measured_at"] = "%d clips / %d videos, %s" % (
        len(paths), len(bysrc), __import__("datetime").date.today().isoformat())
    api("/api/render-styles", st)
    print("targets for %s: saturation %.3f  flatness %.3f  dark %.3f  [%s]"
          % (slug, st["target_saturation"], st["target_flatness"],
             st["target_dark_area"], st["targets_measured_at"]))
    return st


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src", nargs="?"); ap.add_argument("dst", nargs="?")
    ap.add_argument("--style"); ap.add_argument("--target-saturation", type=float)
    ap.add_argument("--saturation", action="store_true", help="match saturation to target")
    ap.add_argument("--palette-lock", action="store_true", help="snap near-palette colours")
    # Measured, not chosen. At strength 0.8 / radius 0.28 the lock made the
    # render WORSE than saturation alone — 1.13 against 1.07 — by dragging
    # flatness and colour the wrong way. At 0.4 / 0.16 it improves on it, 1.03.
    # A palette lock has to nudge; snapping hard destroys the shading that made
    # the flat fills read as deliberate.
    ap.add_argument("--strength", type=float, default=0.4)
    ap.add_argument("--radius", type=float, default=0.16)
    ap.add_argument("--dry-run", action="store_true", help="measure and report, change nothing")
    ap.add_argument("--set-targets", metavar="SLUG")
    ap.add_argument("--from-channel", metavar="CHANNEL")
    a = ap.parse_args(_ARGS)

    if a.set_targets:
        if not a.from_channel:
            ap.error("--set-targets needs --from-channel")
        set_targets(a.set_targets, a.from_channel)
        return 0
    if not (a.src and a.dst):
        ap.error("give src and dst")

    style = get_style(a.style) if a.style else {}
    target = a.target_saturation if a.target_saturation is not None \
        else style.get("target_saturation")
    palette = style.get("palette") or []

    s0, _ = saturation_of(a.src)
    print("input saturation : %.3f" % s0)
    if target is not None:
        print("target           : %.3f  (%s)" % (target, style.get("targets_measured_at") or "given"))
    if a.dry_run:
        if target is not None:
            print("would scale by   : %.2f  (first guess)" % (target / max(s0, 0.01)))
        print("palette          : %s" % (", ".join(palette) or "none"))
        return 0

    with tempfile.TemporaryDirectory() as td:
        cur, chain = a.src, []
        if a.palette_lock:
            if not palette:
                raise SystemExit("--palette-lock needs a style with a measured palette")
            cube = write_cube(os.path.join(td, "p.cube"), palette, a.strength, a.radius)
            out = os.path.join(td, "locked.mp4")
            apply_filters(cur, out, "lut3d=file='%s'" % cube)
            cur = out
            chain.append("palette-lock(strength %.2f, radius %.2f, %d colours)"
                         % (a.strength, a.radius, len(palette)))
            s_after, _ = saturation_of(cur)
            print("after palette    : %.3f" % s_after)

        if a.saturation:
            if target is None:
                raise SystemExit("--saturation needs --style with a target, or "
                                 "--target-saturation")
            best, best_err, best_k = None, None, None
            s_now = saturation_of(cur)[0]
            k = target / max(s_now, 0.01)
            for step in range(3):
                k = float(np.clip(k, 0.2, 3.0))
                out = os.path.join(td, "sat%d.mp4" % step)
                apply_filters(cur, out, "eq=saturation=%.4f" % k)
                s_try = saturation_of(out)[0]
                err = abs(s_try - target)
                print("  pass %d  k=%.3f -> %.3f  (err %.3f)" % (step + 1, k, s_try, err))
                if best_err is None or err < best_err:
                    best, best_err, best_k = out, err, k
                if err < 0.02:
                    break
                # refine: the metric is area-weighted HSV, ffmpeg works in YUV,
                # so the first guess is only ever approximately right
                k = k * (target / max(s_try, 0.01))
            cur = best
            chain.append("saturation(k=%.3f, err %.3f)" % (best_k, best_err))

        if cur == a.src:
            print("nothing to do — pass --saturation and/or --palette-lock")
            return 1
        subprocess.run(["cp", cur, a.dst], check=True)

    s_final, _ = saturation_of(a.dst)
    print("\napplied: %s" % "; ".join(chain))
    print("saturation %.3f -> %.3f%s" % (s0, s_final,
          ("  (target %.3f)" % target) if target is not None else ""))
    print("wrote %s  [%.1f MB]  — input untouched"
          % (a.dst, os.path.getsize(a.dst) / 1e6))
    return 0


if __name__ == "__main__":
    sys.exit(main())
